---

- hosts: all

  tasks:

  - name: Install prereqs
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python3
      - python3-pip

  - name: Add docker repo
    yum_repository:
      name: docker
      description: docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      enabled: yes
  - name: Add Docker GPG Key
    rpm_key:
      key: https://download.docker.com/linux/centos/gpg
      state: present

  - name: Install docker engine
    package:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755
  - name: docker python
    pip:
      name: docker-py
      executable: pip3

  - name: Enable and Start docker
    service:
      name: docker
      state: started
      enabled: yes