---
- name: "install webapp v4"
  become: yes
  hosts: prod
  tasks:
    - name: Generate html redhat
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
      when:
        ansible_os_family == "RedHat"
    - name: Generate html Debian        
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
      when:
        ansible_os_family == "Debian"        
...